### ISSUE TITLE
As a user, I want to browse Discourse hands-free

### ISSUE THREAD

**Issue by BrowseHandsfree** [BrowseHandsfree/handsfree-discourse#1]
BrowseHandsfree will be a forum/community themed around accessibility and creative code. In it, users can create topics and embed sandboxed code from sites like [Glitch.com](https://glitch.com), [CodeSandbox](https://codesandbox.io/), [CodePen](https://codepen.io) and others.

We'll be using [Discourse.org](https://www.discourse.org/) because it's a Single Page Application, meaning we can keep the webcam in the root and navigate around hands-free without ever reloading the model/camera.

For navigating hands-free, we'll be using [Jeeliz](https://jeeliz.com/) - an ultra lightweight deep learning model for head pose and expression recognition.

## Tasks
- [ ] Setup a simple webpack environment, which will minify the Discourse template files
- [ ] Create a simple index.html and web server
- [ ] Start/stop tracker
- [ ] Place a cursor based on where user is facing
- [ ] Activate clicks with various gestures
- [ ] Scroll pages
- [ ] Create a commit script to push the build into a `/discourse` branch, which is where people will load the script from within Discourse

## Announce
- [ ] Tweet (mention Jeeliz and Discourse)

## Topics/Blogs
- [ ] Topic: How to use handsfree-discourse
- [ ] Topic: How we made it
- [ ] Share on Discourse

**Comment by BrowseHandsfree** [comment]
The sandbox (with scrolling) is now accessible at: https://browsehandsfree.firebaseapp.com

![Animated GIF-source (6)](https://user-images.githubusercontent.com/48302421/54232342-af324a00-44c7-11e9-99ce-0c8295838aac.gif)
